# Generated by Django 5.0.1 on 2024-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_age_alter_customer_approved_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(null=True),
        ),
    ]
